### ISSUE TITLE
Wildcard Deku dep 

### ISSUE THREAD

**Issue by stephenmathieson** [fouad/reaku#1]
We use 0.5.6 in production, and am worried about the wildcard in the `package.json`. Is there any reason you're not using semver here?

**Comment by stephenmathieson** [comment]
The `yarn.lock` file suggests the 2.x line, which we can't support :/

https://github.com/fouad/reaku/blob/master/yarn.lock#L17

**Comment by fouad** [comment]
I don't know what version of deku breaks this module, so for now I just left it as `*` in package.json (yarn.lock was a mistake)

**Comment by stephenmathieson** [comment]
IIRC the default export changed somewhere along the line. I'm not sure it'd break anything either, just seeing the wildcard is scary haha
